[workspace]
resolver = "3"
members = [
    "crates/babbel_core",
    "crates/babbel",
    "crates/xml",
    "crates/json",
    "crates/yaml",
    "crates/bencode",
    "crates/toml",
]

[workspace.dependencies]
babbel_core = { path = "crates/babbel_core", version = "0.1.2" }
babbel_xml = { path = "crates/xml", version = "0.1.2" }
babbel_json = { path = "crates/json", version = "0.1.2" }
babbel_yaml = { path = "crates/yaml", version = "0.1.2" }
babbel_bencode = { path = "crates/bencode", version = "0.1.2" }
babbel_toml = { path = "crates/toml", version = "0.1.2" }


[workspace.package]
version = "0.1.2"
authors = ["ClockworkEngineer", "Babbel Contributors"]
edition = "2024"
license = "MIT"
repository = "https://github.com/clockworkengineer/babbel"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.release-small]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 1
incremental = false

[profile.test]
incremental = false
